name: Deploy to GitHub Pages
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Enable corepack
        run: corepack enable
      # Yarn dependencies cannot be cached until yarn is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract cached dependencies
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build
        run: yarn build

      - name: Deploy with gh-pages
        run: |
          git config --global user.email "48921090+roryschadler@users.noreply.github.com"
          git config --global user.name "roryschadler"
          yarn gh-pages \
            --message "${{ steps.tag.outputs.tag }}" \
            --dist dist \
            --repo https://git:${GITHUB_TOKEN}@github.com/roryschadler/roryschadler.github.io.git \
            --user "roryschadler <48921090+roryschadler@users.noreply.github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_ACCESS_TOKEN }}
